# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Purva Tendulkar
email: purva@gatech.edu
description: >- # this means to ignore newlines until "baseurl:"
  Purva is a Computer Science MS student at Georgia Tech, advised by Dr. Devi Parikh.
  Her research interests focus on exploring the creation of AI that can better understand human preferences through the use of common sense reasoning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://purvaten.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PurvaTendulkar
github_username:  purvaten
linkedin_username: purva-tendulkar-774b48151
include: ['_pages']

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
